FROM nginx:alpine

RUN apt-get clean && \
    apt-get update -qq && \
    apt-get install -y --force-yes --fix-missing build-essential \
    libqt4-webkit libqt4-dev xvfb \
    libxml2-dev libxslt1-dev \
    nodejs mysql-client \
    apt-get clean
    gem install bundler

ENV ma_app /var/www/fancybite_fe
RUN mkdir -p $ma_app
WORKDIR $ma_app